import random
from datetime import datetime, timedelta, timezone

from models import Alert, TimelineEvent

ALERTS = [
    {
        "title": "Brute Force Login Attempt Detected",
        "description": "Multiple failed login attempts (47 in 5 minutes) detected from external IP targeting the VPN gateway. Pattern is consistent with credential stuffing using a known breached password list.",
        "severity": "high",
        "source": "Identity & Access Management",
        "source_ip": "185.220.101.34",
        "destination_ip": "10.0.1.50",
        "hostname": "VPN-GW-01",
        "username": "svc_admin",
        "mitre_tactic": "Credential Access",
        "mitre_technique_id": "T1110",
        "mitre_technique_name": "Brute Force",
    },
    {
        "title": "Suspicious PowerShell Execution",
        "description": "Encoded PowerShell command detected executing on workstation. The command includes Base64-encoded payload with network callback to external C2 infrastructure. Triggered by endpoint detection agent.",
        "severity": "critical",
        "source": "Endpoint Detection",
        "source_ip": "10.0.5.112",
        "destination_ip": "91.215.85.142",
        "hostname": "WKS-FIN-042",
        "username": "j.morrison",
        "mitre_tactic": "Execution",
        "mitre_technique_id": "T1059.001",
        "mitre_technique_name": "PowerShell",
    },
    {
        "title": "Malware Hash Detected on Endpoint",
        "description": "Known malicious file hash identified during scheduled scan. File matches signature for Cobalt Strike beacon payload. File was quarantined automatically by endpoint protection.",
        "severity": "critical",
        "source": "Endpoint Detection",
        "source_ip": "10.0.5.112",
        "hostname": "WKS-FIN-042",
        "username": "j.morrison",
        "file_hash": "b326b5062b2f0e69046810717534cb09e678acf0a5c3a050654b1e547c037954",
        "mitre_tactic": "Execution",
        "mitre_technique_id": "T1059",
        "mitre_technique_name": "Command and Scripting Interpreter",
    },
    {
        "title": "DNS Tunneling Activity Detected",
        "description": "Anomalous DNS query pattern identified. Host is making high-frequency TXT record requests to a suspicious domain with encoded subdomain strings, consistent with DNS-based data exfiltration or C2 communication.",
        "severity": "high",
        "source": "Network Monitor",
        "source_ip": "10.0.3.88",
        "destination_ip": "198.51.100.23",
        "hostname": "WKS-DEV-017",
        "username": "k.chen",
        "mitre_tactic": "Command and Control",
        "mitre_technique_id": "T1071",
        "mitre_technique_name": "Application Layer Protocol",
    },
    {
        "title": "Lateral Movement via RDP",
        "description": "Unusual RDP session initiated from a workstation to a database server. The source workstation is not in the approved RDP access list and the connection was made outside business hours.",
        "severity": "high",
        "source": "Network Monitor",
        "source_ip": "10.0.5.112",
        "destination_ip": "10.0.2.30",
        "hostname": "DB-PROD-01",
        "username": "j.morrison",
        "mitre_tactic": "Lateral Movement",
        "mitre_technique_id": "T1021.001",
        "mitre_technique_name": "Remote Desktop Protocol",
    },
    {
        "title": "Credential Dumping Attempt - LSASS Access",
        "description": "Process access to LSASS memory detected on domain controller. The accessing process is an unsigned binary running from a temp directory, consistent with credential harvesting tools like Mimikatz.",
        "severity": "critical",
        "source": "Endpoint Detection",
        "source_ip": "10.0.1.10",
        "hostname": "DC-01",
        "username": "SYSTEM",
        "file_hash": "d41d8cd98f00b204e9800998ecf8427e94187f7c5a1e23d4f0bc6e8a927d3510",
        "mitre_tactic": "Credential Access",
        "mitre_technique_id": "T1003",
        "mitre_technique_name": "OS Credential Dumping",
    },
    {
        "title": "Phishing Email with Malicious Attachment",
        "description": "Email gateway flagged an inbound message with a weaponised Excel attachment containing macros. The sender domain spoofs a known vendor. Three recipients in the finance department received the message.",
        "severity": "medium",
        "source": "Email Security",
        "source_ip": "203.0.113.45",
        "hostname": "MAIL-GW-01",
        "username": "finance-team",
        "file_hash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b856",
        "mitre_tactic": "Initial Access",
        "mitre_technique_id": "T1566",
        "mitre_technique_name": "Phishing",
    },
    {
        "title": "C2 Beacon Communication Detected",
        "description": "Periodic HTTPS callbacks detected at regular 60-second intervals to a known command-and-control IP address. Traffic pattern matches Cobalt Strike malleable C2 profile with jitter.",
        "severity": "critical",
        "source": "Network Monitor",
        "source_ip": "10.0.5.112",
        "destination_ip": "91.215.85.142",
        "hostname": "WKS-FIN-042",
        "username": "j.morrison",
        "mitre_tactic": "Command and Control",
        "mitre_technique_id": "T1105",
        "mitre_technique_name": "Ingress Tool Transfer",
    },
    {
        "title": "Privilege Escalation - Token Manipulation",
        "description": "A standard user process was observed creating a new access token with elevated privileges. The technique is consistent with token impersonation used to gain SYSTEM-level access.",
        "severity": "high",
        "source": "Endpoint Detection",
        "source_ip": "10.0.4.55",
        "hostname": "WKS-HR-008",
        "username": "t.williams",
        "mitre_tactic": "Privilege Escalation",
        "mitre_technique_id": "T1134",
        "mitre_technique_name": "Access Token Manipulation",
    },
    {
        "title": "Unauthorized Cloud API Calls",
        "description": "IAM credentials associated with a service account are making API calls to enumerate S3 buckets and EC2 instances from an unrecognised IP address. The service account key may have been compromised.",
        "severity": "high",
        "source": "Cloud Security",
        "source_ip": "45.33.32.156",
        "hostname": "AWS-PROD",
        "username": "svc_deploy_prod",
        "mitre_tactic": "Discovery",
        "mitre_technique_id": "T1087",
        "mitre_technique_name": "Account Discovery",
    },
    {
        "title": "Data Exfiltration to Cloud Storage",
        "description": "Large volume upload (2.3 GB) detected to an external cloud storage service. The upload originated from a server in the restricted network segment and occurred outside of scheduled backup windows.",
        "severity": "critical",
        "source": "Network Monitor",
        "source_ip": "10.0.2.30",
        "destination_ip": "142.250.70.128",
        "hostname": "DB-PROD-01",
        "username": "j.morrison",
        "mitre_tactic": "Exfiltration",
        "mitre_technique_id": "T1567",
        "mitre_technique_name": "Exfiltration Over Web Service",
    },
    {
        "title": "Scheduled Task Created for Persistence",
        "description": "A new scheduled task was registered to execute a binary from AppData on system startup. The task was created by a non-administrative user and the target binary is not signed.",
        "severity": "medium",
        "source": "Endpoint Detection",
        "source_ip": "10.0.5.77",
        "hostname": "WKS-MKT-023",
        "username": "r.patel",
        "mitre_tactic": "Persistence",
        "mitre_technique_id": "T1053",
        "mitre_technique_name": "Scheduled Task/Job",
    },
    {
        "title": "Network Service Scan Detected",
        "description": "Sequential port scanning activity identified targeting the internal server subnet. Over 500 ports scanned across 12 hosts in under 2 minutes, consistent with automated reconnaissance tooling.",
        "severity": "medium",
        "source": "Network Monitor",
        "source_ip": "10.0.5.112",
        "destination_ip": "10.0.2.0",
        "hostname": "WKS-FIN-042",
        "username": "j.morrison",
        "mitre_tactic": "Discovery",
        "mitre_technique_id": "T1046",
        "mitre_technique_name": "Network Service Discovery",
    },
    {
        "title": "Event Log Clearing Detected",
        "description": "Windows Security event log was cleared on a domain controller. Log clearing during active investigation is a strong indicator of anti-forensics activity by a threat actor.",
        "severity": "high",
        "source": "Endpoint Detection",
        "hostname": "DC-01",
        "username": "admin_backup",
        "mitre_tactic": "Defense Evasion",
        "mitre_technique_id": "T1070",
        "mitre_technique_name": "Indicator Removal",
    },
    {
        "title": "Kerberoasting Activity Detected",
        "description": "Abnormal volume of TGS requests for service accounts detected from a single workstation. The requesting account is a standard user, and the targeted SPNs include high-privilege service accounts.",
        "severity": "high",
        "source": "Identity & Access Management",
        "source_ip": "10.0.4.55",
        "hostname": "WKS-HR-008",
        "username": "t.williams",
        "mitre_tactic": "Credential Access",
        "mitre_technique_id": "T1558",
        "mitre_technique_name": "Steal or Forge Kerberos Tickets",
    },
    {
        "title": "Obfuscated Script Downloaded",
        "description": "A heavily obfuscated JavaScript file was downloaded via browser and written to disk. Static analysis reveals multiple layers of encoding and a deobfuscated payload that attempts to download a second-stage binary.",
        "severity": "medium",
        "source": "Endpoint Detection",
        "source_ip": "10.0.6.14",
        "destination_ip": "104.21.45.67",
        "hostname": "WKS-ENG-031",
        "username": "l.garcia",
        "file_hash": "7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9070",
        "mitre_tactic": "Defense Evasion",
        "mitre_technique_id": "T1027",
        "mitre_technique_name": "Obfuscated Files or Information",
    },
    {
        "title": "Ransomware File Encryption Detected",
        "description": "Rapid file renaming with .locked extension detected across a network share. Over 200 files modified in under 30 seconds with entropy analysis indicating encryption. Consistent with ransomware execution.",
        "severity": "critical",
        "source": "Endpoint Detection",
        "source_ip": "10.0.5.112",
        "hostname": "FS-01",
        "username": "j.morrison",
        "mitre_tactic": "Impact",
        "mitre_technique_id": "T1486",
        "mitre_technique_name": "Data Encrypted for Impact",
    },
    {
        "title": "Suspicious VPN Login - Impossible Travel",
        "description": "VPN authentication from Sydney, AU followed by another from Bucharest, RO within 15 minutes. Geographically impossible travel detected for the same user account.",
        "severity": "medium",
        "source": "Identity & Access Management",
        "source_ip": "86.123.45.67",
        "destination_ip": "10.0.1.50",
        "hostname": "VPN-GW-01",
        "username": "m.anderson",
        "mitre_tactic": "Initial Access",
        "mitre_technique_id": "T1078",
        "mitre_technique_name": "Valid Accounts",
    },
    {
        "title": "Registry Run Key Modification",
        "description": "New registry Run key created pointing to an executable in a user's temp directory. This is a common persistence mechanism used by malware to survive reboots.",
        "severity": "medium",
        "source": "Endpoint Detection",
        "source_ip": "10.0.5.77",
        "hostname": "WKS-MKT-023",
        "username": "r.patel",
        "mitre_tactic": "Persistence",
        "mitre_technique_id": "T1547",
        "mitre_technique_name": "Boot or Logon Autostart Execution",
    },
    {
        "title": "Data Staging on Internal Server",
        "description": "Large compressed archive (780 MB) created in a staging directory on the file server. The archive contains files collected from multiple departmental shares, suggesting pre-exfiltration data staging.",
        "severity": "high",
        "source": "Endpoint Detection",
        "source_ip": "10.0.2.30",
        "hostname": "FS-01",
        "username": "j.morrison",
        "mitre_tactic": "Collection",
        "mitre_technique_id": "T1560",
        "mitre_technique_name": "Archive Collected Data",
    },
    {
        "title": "Web Application SQL Injection Attempt",
        "description": "WAF detected multiple SQL injection payloads in HTTP POST parameters targeting the customer portal login form. Attack originated from a known malicious IP with prior scanning history.",
        "severity": "medium",
        "source": "Web Application Firewall",
        "source_ip": "192.0.2.100",
        "destination_ip": "10.0.3.10",
        "hostname": "WEB-PROD-01",
        "mitre_tactic": "Initial Access",
        "mitre_technique_id": "T1190",
        "mitre_technique_name": "Exploit Public-Facing Application",
    },
    {
        "title": "DDoS Attack Detected on Public API",
        "description": "Volumetric traffic spike detected targeting the public API gateway. Traffic volume reached 4.2 Gbps from distributed sources, causing intermittent service degradation.",
        "severity": "high",
        "source": "Network Monitor",
        "source_ip": "Multiple",
        "destination_ip": "10.0.3.10",
        "hostname": "API-GW-01",
        "mitre_tactic": "Impact",
        "mitre_technique_id": "T1498",
        "mitre_technique_name": "Network Denial of Service",
    },
    {
        "title": "Suspicious DNS Query to DGA Domain",
        "description": "DNS resolution attempt for domain matching known DGA (Domain Generation Algorithm) pattern. The queried domain has high entropy and was registered within the last 24 hours.",
        "severity": "medium",
        "source": "Network Monitor",
        "source_ip": "10.0.6.14",
        "destination_ip": "198.51.100.23",
        "hostname": "WKS-ENG-031",
        "username": "l.garcia",
        "mitre_tactic": "Command and Control",
        "mitre_technique_id": "T1071",
        "mitre_technique_name": "Application Layer Protocol",
    },
    {
        "title": "MFA Bypass Attempt Detected",
        "description": "Repeated MFA push notifications sent to a user account (12 in 3 minutes) without successful authentication. Pattern consistent with MFA fatigue attack attempting to get the user to approve a fraudulent login.",
        "severity": "high",
        "source": "Identity & Access Management",
        "source_ip": "103.45.67.89",
        "hostname": "AUTH-01",
        "username": "c.taylor",
        "mitre_tactic": "Credential Access",
        "mitre_technique_id": "T1110",
        "mitre_technique_name": "Brute Force",
    },
    {
        "title": "Unusual Data Transfer via SFTP",
        "description": "Abnormal SFTP transfer of 1.8 GB from a development server to an external IP address not in the approved transfer list. The transfer was initiated by a service account outside of maintenance windows.",
        "severity": "high",
        "source": "Network Monitor",
        "source_ip": "10.0.4.20",
        "destination_ip": "156.67.89.12",
        "hostname": "DEV-SVR-03",
        "username": "svc_backup",
        "mitre_tactic": "Exfiltration",
        "mitre_technique_id": "T1048",
        "mitre_technique_name": "Exfiltration Over Alternative Protocol",
    },
    {
        "title": "UAC Bypass Attempt Detected",
        "description": "Process execution chain detected that matches known UAC bypass technique (fodhelper.exe method). A medium-integrity process spawned a high-integrity child process without UAC prompt.",
        "severity": "medium",
        "source": "Endpoint Detection",
        "source_ip": "10.0.5.77",
        "hostname": "WKS-MKT-023",
        "username": "r.patel",
        "mitre_tactic": "Privilege Escalation",
        "mitre_technique_id": "T1548",
        "mitre_technique_name": "Abuse Elevation Control Mechanism",
    },
    {
        "title": "Failed SSH Logins from Internal Host",
        "description": "Over 30 failed SSH login attempts from an internal workstation to multiple Linux servers in the production environment. This lateral movement pattern suggests compromised credentials or an insider threat.",
        "severity": "medium",
        "source": "Network Monitor",
        "source_ip": "10.0.4.55",
        "destination_ip": "10.0.2.0",
        "hostname": "Multiple Linux servers",
        "username": "t.williams",
        "mitre_tactic": "Lateral Movement",
        "mitre_technique_id": "T1021",
        "mitre_technique_name": "Remote Services",
    },
]


def seed_database(db):
    if db.query(Alert).count() > 0:
        return

    now = datetime.now(timezone.utc)
    rng = random.Random(42)

    for i, alert_data in enumerate(ALERTS):
        hours_ago = rng.randint(1, 30 * 24)
        created = now - timedelta(hours=hours_ago)

        statuses = ["open"] * 5 + ["investigating"] * 3 + ["resolved"] * 2
        status = rng.choice(statuses)

        alert = Alert(
            **alert_data,
            status=status,
            created_at=created,
            updated_at=created + timedelta(minutes=rng.randint(0, 120)),
        )
        db.add(alert)
        db.flush()

        timeline = TimelineEvent(
            alert_id=alert.id,
            event_type="alert_created",
            description=f"Alert created: {alert.title}",
            created_at=created,
        )
        db.add(timeline)

        if status != "open":
            status_time = created + timedelta(minutes=rng.randint(5, 60))
            db.add(
                TimelineEvent(
                    alert_id=alert.id,
                    event_type="status_change",
                    description=f"Status changed from open to {status}",
                    created_at=status_time,
                )
            )

    db.commit()
